apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-product-configmap
  labels:
    app: product-postgres
data:
  POSTGRES_DB: product
  POSTGRES_USER: docker
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-product-secrets
data:
  POSTGRES_PASSWORD: root
stringData:
  POSTGRES_USER: docker
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-product-pv-volume
  labels:
    type: local
    app: product-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/pgdata/product/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-product-pv-claim
  labels:
    app: product-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-postgres
spec:
  selector:
    matchLabels:
      app: product-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: product-postgres
    spec:
      containers:
        - name: product-postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
          - secretRef:
              name: postgres-product-secrets
          - configMapRef:
              name: postgres-product-configmap  
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-product-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: product-postgres
  labels:
    app: product-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: product-postgres