apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb
data:
  database-name: microservices
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:  
  database-user: dGVzdAo=
  database-password: ZXhhbXBsZQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: josecarloslopez/mongodb-microservicios:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongodb        