# Spring properties
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_products
  # spring boot admin client
  boot:
    admin:      
      client:
        url: http://localhost:8080/admin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

# Expose all the Actuator endpoints
management:
  endpoints:
    web:
      exposure:        
        include: "*"

# HTTP Server
server:
  port: 82

# feign error control
hystrix:
  shareSecurityContext: true  
feign:
  hystrix:
    enabled: true
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# Auth JWT
jwt:
  header: Authorization
  secret: secret_secret
  expiration: 172800 #seconds
  route:
    authentication:
      path: auth
      refresh: refresh

