# Spring properties
spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_products
  # spring boot admin client
  boot:
    admin:      
      client:
        url: http://localhost:8080/admin
  # rabbit mq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
# Event bus
app:
  rabbitmq:
    queue: QueueCommon
    topic: spring-boot-exchange
    expiration: 5000

# Expose all the Actuator endpoints
management:
  endpoints:
    web:
      exposure:        
        include: "*"        

# HTTP Server
server:
  port: 81
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# Auth JWT
jwt:
  header: Authorization
  secret: secret_secret
  expiration: 172800 #seconds
  route:
    authentication:
      path: auth
      refresh: refresh

# Image Upload Location
image:
  upload:
    location: C:/images
    
# Email
email:
  userName: test@gmail.com
  password: test
