# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
       
# HTTP Server
server:
  port: @http.port@
  
# Expose all the Actuator endpoints
management:
  endpoints:
    web:
      exposure:        
        include: "*"
  